# Generated by Django 3.2 on 2021-05-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeid',
            field=models.CharField(default=0, max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
