# Generated by Django 3.2 on 2021-05-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210514_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='post',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Место'),
            preserve_default=False,
        ),
    ]
