# Generated by Django 3.2 on 2021-05-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20210514_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='post',
            new_name='place',
        ),
    ]
