# Generated by Django 3.2 on 2021-06-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20210601_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='placeid',
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='places.place', verbose_name='Место'),
        ),
    ]
