# Generated by Django 3.2 on 2021-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_place_placeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='lat',
            field=models.FloatField(default=0, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lng',
            field=models.FloatField(default=0, null=True, verbose_name='Долгота'),
        ),
    ]
