# Generated by Django 3.2 on 2021-06-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_auto_20210617_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='lat',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lng',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Место'),
        ),
    ]
