# Generated by Django 3.2 on 2021-06-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_auto_20210617_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lng',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
