# Generated by Django 3.2 on 2021-06-17 14:59

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0026_alter_coordinates_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='lat',
            field=models.FloatField(default=1.0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lng',
            field=models.FloatField(default=1.0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='place',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='places.place', verbose_name='Место'),
        ),
    ]
