# Generated by Django 3.2 on 2021-06-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0028_auto_20210617_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='places.place', verbose_name='Место'),
        ),
    ]
