# Generated by Django 3.2 on 2021-06-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_alter_coordinates_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='places.place', verbose_name='Место'),
        ),
    ]
